location = "local-3"
server_id = 3
num_clients = 0 # Hardcoded number of client connections to wait for
output_filepath = "../benchmarks/logs/local-run/server-3.json"
# Cluster-wide settings
local_deployment = true # use localhost
cluster_name = "local-cluster"
nodes = [1, 2, 3]
initial_leader = 1
initial_flexible_quorum = { read_quorum_size = 2, write_quorum_size = 2 }
